version: "3.7"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
